codecov:
  require_ci_to_pass: yes
  token: d62ebc6a-bb0f-4bb7-a644-602d0ccf8eeb

coverage:
  precision: 2
  range: "60...85"
  status:
    project:
      default:
        target: auto
        # adjust accordingly based on how flaky your tests are
        # this allows a 10% drop from the previous base commit coverage
        threshold: 10%
