name: Testing Workflow

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm install
          npm run build
      - name: Run test and report issues
        run: npm test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          fail_ci_if_error: true # opcional (valor por defecto = false)
          token: YOUR_CODECOV_TOKEN # Replace with your actual token
          verbose: true # opcional (valor por defecto = false)
          slug: dileofrancoj/git-workflow
          coverage:
            status:
              # Use 'patch' for pull request coverage reporting
              patch:
                default:
                  # Basic configuration
                  target: auto # Default target
                  threshold: 0%
                  base: auto # Use historical data from the target branch
                  # Advanced configuration (optional)
                  # flags:
                  #   - unit  # Uncomment if applicable

                  paths:
                    - "src" # Path to your test coverage files
