name: Testing Workflow

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm install
          npm run build
      - name: Run test and report issues
        run: npm test

      # Step to upload coverage to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          fail_ci_if_error: true
          token: d62ebc6a-bb0f-4bb7-a644-602d0ccf8eeb
          verbose: true
          slug: dileofrancoj/git-workflow

      # Additional steps for coverage and flag management
      - name: Configure coverage status
        run: |
          echo "coverage:" >> .codecov.yml
          echo "  status:" >> .codecov.yml
          echo "    project: off" >> .codecov.yml
          echo "    patch: off" >> .codecov.yml

      - name: Configure flag management
        run: |
          echo "flag_management:" >> .codecov.yml
          echo "  individual_flags:" >> .codecov.yml
          echo "    - name: backend" >> .codecov.yml
          echo "      paths:" >> .codecov.yml
          echo "        - api/" >> .codecov.yml
          echo "      statuses:" >> .codecov.yml
          echo "        - type: project" >> .codecov.yml
          echo "          target: 100%" >> .codecov.yml
          echo "          threshold: 50%" >> .codecov.yml
          echo "    - name: frontend" >> .codecov.yml
          echo "      paths:" >> .codecov.yml
          echo "        - web/" >> .codecov.yml
          echo "      statuses:" >> .codecov.yml
          echo "        - type: project" >> .codecov.yml
          echo "          target: auto" >> .codecov.yml
          echo "          threshold: 50%" >> .codecov.yml
