name: Testing Workflow

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm install
          npm run build
      - name: Run test and report issues
        run: npm test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true # opcional (valor por defecto = false)
          token: de8bdfd9-e504-4776-88ee-686acfa30094
          verbose: true # opcional (valor por defecto = false)
          slug: dileofrancoj/git-workflow
